platform :ios, '5.0'
#pod 'AFNetworking', '~> 1.0.1'
#pod 'AQGridView','~> 1.3'
#pod 'DAKeyboardControl','~> 0.0.1'
#pod 'DDProgressView','~> 0.1'
#pod 'HPGrowingTextView','~> 0.0.1'
#pod 'JSONKit','~> 1.5pre'
pod 'MFSideMenu','~> 0.3'
pod 'MGBox2','~> 1.3.0'
#pod 'MTStatusBarOverlay','~> 0.9'
#pod 'ODRefreshControl',:git => 'https://github.com/creativemess/ODRefreshControl.git'
pod 'OHAttributedLabel','~> 1.2.0'
pod 'PrettyKit','~> 0.2.0'
#pod 'RegexKitLite','~> 4.0'
#pod 'RestKit','~> 0.10.3'
pod 'SDWebImage','~> 2.7.0'
#pod 'SVProgressHUD',:git => 'https://github.com/creativemess/SVProgressHUD.git'
#pod 'vfrReader',:git => 'https://github.com/creativemess/vfrReader.git'